[manifest]
version = "1.0.0"
priority = 0

#Context for 'Cerulean Bell' to select a held card after drawing
[[patches]]
[patches.pattern]
target = "blind.lua"
pattern = 'function Blind:drawn_to_hand()'
position = "after"
payload = '''
    -- chicot drawn_to_hand_context.toml - patch start
    SMODS.calculate_context({chic_drawn_to_hand = true})
    -- patch end

'''
match_indent = true