[manifest]
version = "1.0.0"
priority = 0

#Context for 'The Arm' to retrigger hand level ups
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = 'function level_up_hand(card, hand, instant, amount)'
position = "after"
payload = '''
    -- chicot level_up_context.toml - patch start
    local effects
    SMODS.calculate_context({chic_leveled_up = true, card = card, hand = hand, instant = instant, amount = amount}, effects)
    -- patch end

'''
match_indent = true